export const PATHS = Object.freeze({
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_EMAIL_CALLBACK: '/verify-email/:id/:hash',
  EMAIL_VERIFIED: '/email-verified',

  EXPERT_LOGIN: '/expert/login',
  EXPERT_REGISTER: '/expert/register',
  EXPERT_FORGOT_PASSWORD: '/expert/forgot-password',
  EXPERT_RESET_PASSWORD: '/expert/reset-password',
  EXPERT_VERIFY_EMAIL: '/expert/verify-email',
  EXPERT_VERIFY_EMAIL_CALLBACK: '/expert/verify-email/:id/:hash',
  EXPERT_EMAIL_VERIFIED: '/expert/email-verified',
  EXPERT_DASHBOARD: '/expert/dashboard',
  EXPERT_PROFILE: '/expert/profile',
  EXPERT_KYC: '/expert/kyc',

  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_CASES: '/admin/cases',
  ADMIN_EXPERTS: '/admin/experts',
  ADMIN_USERS: '/admin/users',
  ADMIN_COMPLAINTS: '/admin/complaints',
  ADMIN_RISK: '/admin/risk',
  ADMIN_DISPUTES: '/admin/disputes',
  ADMIN_POLICIES: '/admin/policies',
  ADMIN_AUDIT: '/admin/audit',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_ROLE_CREATE: '/admin/roles/new',
  ADMIN_SUB_ADMINS: '/admin/sub-admins',
  ADMIN_KYC: '/admin/kyc',
  ADMIN_KYC_REVIEW: '/admin/kyc/:kycId',
  ADMIN_SETTINGS: '/admin/settings',

  USER_DASHBOARD: '/app/dashboard',
  USER_CASES: '/app/cases',
  USER_CASE_NEW: '/app/cases/new',
  USER_CASE_WORKSPACE: '/app/cases/current',
  USER_EXPERTS: '/app/experts',
  USER_CONSULTATIONS: '/app/consultations',
  USER_PROFILE: '/app/profile',
});
